kind: PersistentVolumeClaim
metadata:
  name: {{ template "dartserver.fullname" . }}
  labels:
    app: {{ template "dartserver.name" . }}
    chart: {{ template "dartserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
 storageClassName: {{ .Values.storageClassName | quote }}
 accessModes:
    - "ReadWriteMany"
 resources:
   requests:
     storage: {{ .Values.capacity | quote }}
#  selector: 
#     matchLabels:
#       pvc : {{ .Values.name | quote }}   